// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbctfpztpslxsxdbtfxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiY3RmcHp0cHNseHN4ZGJ0ZnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTA5NjksImV4cCI6MjA2NjUyNjk2OX0.eeLcXvbzcZNH2GiZCprKHTfJD5ljf6CAYbQgAO8s_tU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);